### ISSUE TITLE
Bug: Config file needs to specify commandLineArgs as "--j" when it actually means "-j"

### ISSUE THREAD

**Issue by mczarneka2i** [rooseveltframework/source-configs#198]
First of all, I love this library as a way to use a config file for setting the configuration, with the easy possibility to overwrite with command line args!  Thank you very much to those who made it!

Found a bug though, I created a config file (minimally reproducible example below) and I load it and it's fine until I try to use command line parameters to set settings. if I add "-jawky" to the command line, then it will set "jawkyoff" to true, as desired. However, if I add "-j", then it ignores it and the value remains false.

I accidentally stumbled across a workaround though (some might consider it a bug itself), if instead of specifying "commandLineArg": ["-j","--jawky"], I specify it as "commandLineArg": ["--j","--jawky"]  (note extra "-"), then it will accept "-j" as a command line switch and change the value of "jawkyoff" to true.

config-hypnos-backend.json
```
{
  "config": {
      "jawkyoff": {
          "description": "Disable JawkyDocker for Windows running and development",
          "default": false,
          "commandLineArg": ["-j","--jawky"]
      }
  }
}
```

js code
```
let sourceConfigs = require('source-configs');

const configFile = require('./config-hypnos-backend');

const config = sourceConfigs(configFile, {
  transform: (config, commandLineArgs) => {

    console.log(config);  //using this to check what config is being set to
 
    // return the config when done
    return config
  }
})
```

**Comment by Autre31415** [comment]
I've been able to replicate this in tests. Thank you for the rigorous report!
