### ISSUE TITLE
Simplify acceptedValues

### ISSUE THREAD

**Issue by lannonbr** [rooseveltframework/source-configs#6]
Update acceptedValues to be a simple array. if the item is not one of the accepted values, return the default value instead

**Comment by lannonbr** [comment]
@kethinov, if there is no default value for the config property, I will send an error to the console, but should we keep the invalid enum that was provided or set the config property to null?

**Comment by kethinov** [comment]
null

**Comment by lannonbr** [comment]
Okay. That is what I ended up going with in the PR
