### ISSUE TITLE
Add ability to look for config params at a specified prefix

### ISSUE THREAD

**Issue by reecer62** [rooseveltframework/source-configs#82]
When source-configs grabs the config file, allow a prefix to be used and ignore everything else.
For example, say we have a deployConfig.json file that is structured as such:

```
{
    rooseveltConfig: {
        port: 1234
    },
    port: 11111,
    .
    .
    .
}
```
Allow a parameter/prefix to be passed in that only looks at specific section of the config. For this example, you could pass in 'rooseveltConfig' as a parameter and source-configs would only look at the `rooseveltConfig` object.

**Comment by kethinov** [comment]
superseded by https://github.com/rooseveltframework/roosevelt/issues/746
