### ISSUE TITLE
Allow for user defined parsing functions

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/source-configs#89]
It would be nice to be able to use a custom parsing function for a particular config. Especially to help with parsing env variables

**Comment by kethinov** [comment]
Does [this](https://github.com/rooseveltframework/source-configs#user-defined-functions) not do what you need?

**Comment by kethinov** [comment]
Closing this. Reopen if [this](https://github.com/rooseveltframework/source-configs#user-defined-functions) doesn't do what you need.
